version: "3.8"
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=retaurant
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - nestjs-network
networks:
  nestjs-network:
    driver: bridge
#run docker-compose up -d
#down docker-compose down
